name: Book

on:
  push:
    branches:
      - '**'
    tags:
      - '!**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build the book
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          sudo apt update
          sudo apt install python3-polib libxml2-utils xsltproc docbook-xml docbook-xsl tidy fop gettext
      - name: Install po4a-0.62
        run: |
          wget 'https://bf.mengyan1223.wang/assets/po4a/po4a_0.62-xry111-1_all.deb'
          sudo apt install ./po4a_0.62-xry111-1_all.deb
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check for Untranslated or Fuzzy Strings
        run: ./check-translations.sh
      - name: Set Environment for Pull Requests
        if: github.event_name != 'push'
        run: |
          echo "UPLOAD=no" >> $GITHUB_ENV
          echo "SVN_BRANCH=trunk/BOOK" >> $GITHUB_ENV
      - name: Set Environment for Push
        if: github.event_name == 'push'
        run: ./setenv.sh "${GITHUB_REF}"
      - name: Configure
        run: |
          echo 'MLANG=zh_CN' > local.mk
      - name: Update po Files
        run: make pofiles
      - name: Generate Translated XML Files
        run: make booksrc
      - name: Generate Translated Book (sysv)
        run: |
          make REV=sysv html nochunks pdf
          mv zh_CN/book/render lfs-sysv
          mv zh_CN/book/nochunks/* lfs-sysv
          mv zh_CN/book/pdf/* lfs-sysv
      - name: Generate Translated Book (systemd)
        run: |
          make REV=systemd html nochunks pdf
          mv zh_CN/book/render lfs-systemd
          mv zh_CN/book/nochunks/* lfs-systemd
          mv zh_CN/book/pdf/* lfs-systemd
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: book
          path: |
            lfs-sysv 
            lfs-systemd
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Upload Generated Book to the Server
        if: env.UPLOAD == 'yes'
        run: |
          cat .known_hosts >> $HOME/.ssh/known_hosts
          ssh "lfsbook@mengyan1223.wang" rm -rf "/var/www/xry111/lfs/zh_CN/${SYSV}"
          ssh "lfsbook@mengyan1223.wang" rm -rf "/var/www/xry111/lfs/zh_CN/${SYSD}"
          scp -r lfs-sysv "lfsbook@mengyan1223.wang:/var/www/xry111/lfs/zh_CN/${SYSV}"
          scp -r lfs-systemd "lfsbook@mengyan1223.wang:/var/www/xry111/lfs/zh_CN/${SYSD}"
